### ISSUE TITLE
No faces appearing in readme

### ISSUE THREAD

**Issue by jdshkolnik** [ngryman/contributor-faces#29]
What more am I supposed to do besides running npm install and adding the placeholder somewhere in the markdown file? Should the faces of all repo contributors suddenly appear?

**Comment by ngryman** [comment]
Hey, sorry you had trouble using this package. It's up to you to call the CLI `contributor-faces` [command](https://github.com/ngryman/contributor-faces#cli) to update your `README`. Does it work for you when you do that?

**Comment by PeterNgTr** [comment]
@ngryman same for me. Readme file is not updated after calling the CLI contributor-faces cmd.

**Comment by PeterNgTr** [comment]
nvm! It worked for me after adding the placeholder in the readme markdown file.

**Comment by ngryman** [comment]
Awesome that it worked, closing the issue!
